name: Create repository on push

on:
  push:
    branches:
      - master

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Check if repository exists
        run: |
          if [ -d "$GITHUB_REPOSITORY" ]; then
            echo "Repository already exists"
            exit 0
          fi

      - name: Create repository
        run: |
          git init
          git add .
          git commit -m "Initial commit"
          git push -u origin master

      - name: Set branch to master
        run: |
          git checkout master
